MyVet/Controllers/AuthController.cs
using Infraestructure.Entity.Model;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using MyVet.Domain.Dto;
using MyVet.Domain.Services.Interface;
using MyVet.Handlers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using static Common.Utils.Constant.Const;

namespace MyVet.Controllers
{
    [TypeFilter(typeof(CustomExceptionHandler))]
    public class AuthController : Controller
    {
        private readonly IUserServices _userServices;

        public AuthController(IUserServices userServices)
        {
            _userServices = userServices;
        }


        [HttpGet]
        public IActionResult Login()
        {
            return View(new UserDto());
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserDto user)
        {
            ResponseDto response = _userServices.Login(user);

            if (!response.IsSuccess)
            {
                ModelState.Clear();
                ModelState.AddModelError(string.Empty, response.Message);
                return View(user);
            }
            else
            {

                UserEntity userEntity = (UserEntity)response.Result;


                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, userEntity.FullName),
                    new Claim(TypeClaims.IdUser, userEntity.IdUser.ToString()),
                    new Claim(TypeClaims.UserName, userEntity.Email),
                    new Claim(TypeClaims.IdRol, string.Join(",",userEntity.RolUserEntities.Select(x=>x.IdRol))),
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    //AllowRefresh = <bool>,
                    // Refreshing the authentication session should be allowed.

                    ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(60),
                    // The time at which the authentication ticket expires. A 
                    // value set here overrides the ExpireTimeSpan option of 
                    // CookieAuthenticationOptions set with AddCookie.

                    IsPersistent = false,
                    // Whether the authentication session is persisted across 
                    // multiple requests. When used with cookies, controls
                    // whether the cookie's lifetime is absolute (matching the
                    // lifetime of the authentication ticket) or session-based.

                    //IssuedUtc = <DateTimeOffset>,
                    // The time at which the authentication ticket was issued.

                    //RedirectUri = <string>
                    // The full path or absolute URI to be used as an http 
                    // redirect response value.
                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                                              new ClaimsPrincipal(claimsIdentity),
                                              authProperties);

                return Redirect("/Home/Index");
            }
        }


        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(nameof(Login));
        }


        [HttpGet]
        public IActionResult Register()
        {
            return View(new UserDto());
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserDto user)
        {
            IActionResult response;

            var result = await _userServices.Register(user);
            if (!result.IsSuccess)
            {
                ModelState.Clear();
                ModelState.AddModelError(string.Empty, result.Message);
                return View(user);
            }
            else
            {
                response = RedirectToAction(nameof(Login));
            }
            return response;
        }
    }
}

MyVet/Controllers/DatesController.cs
using Infraestructure.Entity.Model.Vet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyVet.Domain.Dto;
using MyVet.Domain.Services.Interface;
using MyVet.Handlers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static Common.Utils.Constant.Const;

namespace MyVet.Controllers
{
    [Authorize]
    [TypeFilter(typeof(CustomExceptionHandler))]
    public class DatesController : Controller
    {
        #region Attributes
        private readonly IDatesServices _datesServices;
        #endregion

        #region Builder
        public DatesController(IDatesServices datesServices)
        {
            _datesServices = datesServices;
        }
        #endregion


        #region Views
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult DatesVet()
        {
            return View();
        }

        #endregion


        #region Methods
        [HttpGet]
        public IActionResult GetAllDates()
        {
            var user = HttpContext.User;
            string idUser = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.IdUser)!.Value;

            List<DatesDto> result = _datesServices.GetAllDates(Convert.ToInt32(idUser));
            return Ok(result);
        }

        [HttpGet]
        public IActionResult GetAllMyDates()
        {
            var user = HttpContext.User;
            string idUser = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.IdUser)!.Value;

            List<DatesDto> result = _datesServices.GetAllMyDates(Convert.ToInt32(idUser));
            return Ok(result);
        }

        [HttpGet]
        public IActionResult GetAllServices()
        {
            List<ServicesEtntity> result = _datesServices.GetAllServices();
            return Ok(result);
        }

        [HttpPost]
        public async Task<IActionResult> InsertDates(DatesDto dates)
        {
            bool result = await _datesServices.InsertDatesAsync(dates);
            return Ok(result);
        }

        [HttpPut]
        public async Task<IActionResult> UpdateDates(DatesDto dates)
        {
            bool result = await _datesServices.UpdateDatesAsync(dates);
            return Ok(result);
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteDates(int idDates)
        {
            ResponseDto result = await _datesServices.DeleteDatesAsync(idDates);
            return Ok(result);
        }

        [HttpGet]
        public async Task<IActionResult> CancelDates(int idDates)
        {
            bool result = await _datesServices.CancelDatesAsync(idDates, idUserVet: null);
            return Ok(result);
        }

        [HttpPut]
        public async Task<IActionResult> UpdateDatesVet(DatesDto dates)
        {
            var user = HttpContext.User;
            string idUser = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.IdUser).Value;
            dates.IdUserVet = Convert.ToInt32(idUser);

            bool result = await _datesServices.UpdateDatesVetAsync(dates);
            return Ok(result);
        }

        [HttpGet]
        public async Task<IActionResult> CancelDatesVet(int idDates)
        {
            var user = HttpContext.User;
            string idUser = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.IdUser).Value;

            bool result = await _datesServices.CancelDatesAsync(idDates, Convert.ToInt32(idUser));
            return Ok(result);
        }


        #endregion
    }
}

MyVet/Controllers/PetController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyVet.Domain.Dto;
using MyVet.Domain.Services.Interface;
using MyVet.Handlers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static Common.Utils.Constant.Const;

namespace MyVet.Controllers
{
    [Authorize]
    [TypeFilter(typeof(CustomExceptionHandler))]
    public class PetController : Controller
    {
        #region Attribute
        private readonly IPetServices _petServices;
        #endregion

        #region Buider
        public PetController(IPetServices petServices)
        {
            _petServices = petServices;

        }
        #endregion

        #region Methods

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("GetAllMyPets")]
        public IActionResult GetAllMyPets()
        {
            var user = HttpContext.User;
            string idUser = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.IdUser)!.Value;
            List<PetDto> list = _petServices.GetAllMyPets(Convert.ToInt32(idUser));

            return Ok(list);
        }

        [HttpGet("GetAllPets")]
        public IActionResult GetAllPets()
        {
            //List<PetDto> list = _petServices.GetAllPets();

            return Ok(new List<PetDto>());
        }


        [HttpDelete]
        public async Task<IActionResult> DeletePet(int idPet)
        {
            ResponseDto response = await _petServices.DeletePetAsync(idPet);
            return Ok(response);
        }

        [HttpGet]
        public IActionResult GetAllSexs()
        {
            List<SexDto> response = _petServices.GetAllSexs();
            return Ok(response);
        }

        [HttpGet]
        public IActionResult GetAllTypePet()
        {
            List<TypePetDto> response = _petServices.GetAllTypePet();
            return Ok(response);
        }

        [HttpPost]
        public async Task<IActionResult> InsertPet(PetDto pet)
        {
            var user = HttpContext.User;
            string idUser = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.IdUser).Value;
            pet.IdUser = Convert.ToInt32(idUser);

            bool response = await _petServices.InsertPetAsync(pet);
            return Ok(response);
        }

        [HttpPut]
        public async Task<IActionResult> UpdatePet(PetDto pet)
        {
            bool response = await _petServices.UpdatePetAsync(pet);
            return Ok(response);
        }
        #endregion
    }
}

MyVet/Controllers/UserController.cs
using Infraestructure.Entity.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyVet.Domain.Services.Interface;
using MyVet.Handlers;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using static Common.Utils.Constant.Const;

namespace MyVet.Controllers
{
    [Authorize]
    [TypeFilter(typeof(CustomExceptionHandler))]
    public class UserController : Controller
    {
        private readonly IUserServices _userServices;
        private readonly IRolServices _rolServices;

        public UserController(IUserServices userServices, IRolServices rolServices)
        {
            _userServices = userServices;
            _rolServices = rolServices;
        }


        [HttpGet]
        public IActionResult Index()
        {
            //FormAuthentication.
            List<UserEntity> users = _userServices.GetAll();
            return View(users);
        }


        [HttpGet]
        public IActionResult Edit(int? id)
        {
            IActionResult response;

            if (id == null)
                response = NotFound();

            UserEntity user = _userServices.GetUser((int)id);
            if (user == null)
            {
                response = NotFound();
            }
            else
            {
                response = View(user);
            }

            return response;
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserEntity user)
        {

            var rtok = Request.Headers["Authorization"];

            var loggedInUser = HttpContext.User;
            var loggedInUserName = loggedInUser.Identity.Name; // This is our username we set earlier in the claims. 
            var loggedInUserName2 = loggedInUser.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name).Value; //Another way to get the name or any other claim we set. 
            var loggedInUserName3 = loggedInUser.Claims.FirstOrDefault(x => x.Type == TypeClaims.IdRol).Value; //Another way to get the name or any other claim we set. 


            IActionResult response;

            bool result = await _userServices.UpdateUser(user);
            if (result)
            {
                response = RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError(string.Empty, "No se pudo Actualizar el Usuario");
                response = RedirectToAction(nameof(Index));
            }
            return response;
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            IActionResult response;

            if (id == null)
                response = NotFound();

            UserEntity user = _userServices.GetUser((int)id);
            if (user == null)
            {
                response = NotFound();
            }
            else
            {
                response = View(user);
            }

            return response;
        }


        [HttpPost]
        public async Task<IActionResult> ConfirmDelete(int IdUser)
        {
            IActionResult response;
            if (IdUser == 0)
                response = NotFound();

            else
            {
                bool result = await _userServices.DeleteUser(IdUser);
                if (result)
                {
                    response = RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "No se pudo Actualizar el Usuario");
                    response = RedirectToAction(nameof(Index));
                }
            }

            return response;
        }


        [HttpGet]
        public IActionResult Create()
        {
            ViewData["Roles"] = new SelectList(_rolServices.GetAll(), "IdRol", "Rol");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserEntity user)
        {
            IActionResult response;

            var result = await _userServices.CreateUser(user);
            if (result.IsSuccess)
            {
                response = RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["Roles"] = new SelectList(_rolServices.GetAll(), "IdRol", "Rol");
                ModelState.AddModelError(string.Empty, result.Message);
                response = View(user);
            }
            return response;
        }
    }
}

MyVet/Views/Shared/_Layout.cshtml
@using Common.Utils.Enums
@using Microsoft.AspNetCore.Identity
@using static Common.Utils.Constant.Const
@{
    var idRols = User.Claims.FirstOrDefault(x => x.Type == TypeClaims.IdRol).Value;

    bool isAdmin = idRols.Any(x => x.ToString() == Convert.ToInt32(Enums.RolUser.Administrador).ToString());
    bool isVet = idRols.Any(x => x.ToString() == Convert.ToInt32(Enums.RolUser.Veterinario).ToString());
    bool isStandar = idRols.Any(x => x.ToString() == Convert.ToInt32(Enums.RolUser.Estandar).ToString());

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyVet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />

    @*Datable*@
    <link rel="stylesheet" href="~/lib/dataTable/datatables.min.css" />
    <link rel="stylesheet" href="~/lib/dataTable/DataTables-1.13.3/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" href="~/lib/dataTable/Buttons-2.3.5/css/buttons.bootstrap4.min.css" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyVet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @if (User != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" title="Manage">Hola @User.Identity.Name!</a>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" asp-area="" asp-controller="Auth" asp-action="Logout" method="get">
                                    <button type="submit" class="nav-link btn btn-link text-dark"> <i class="fas fa-sign-out-alt"></i>  Salir</button>
                                </form>
                            </li>
                        }
                    </ul>


                    <ul class="navbar-nav flex-grow-1">
                        @if (isAdmin)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pet" asp-action="Index">Mascotas</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dates" asp-action="DatesVet">Citas Disponibles</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contacto</a>
                            </li>
                        }
                        else if (isVet)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dates" asp-action="DatesVet">Citas Disponibles</a>
                            </li>
                        }
                        else if (isStandar)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pet" asp-action="Index">Mis Mascotas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dates" asp-action="Index">Mis Citas</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="modal fade" id="container-modal-procesando" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body" style="text-align:center;font-weight:bold">
                    <p id="mensaje-modal-procesando">Por favor espere</p>
                    <div align="center"><img width="100%" src="~/img/loading-97.gif"></div>
                </div>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - MyVet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> - <a asp-area="" asp-controller="Home" asp-action="Contact">Contáctanos</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"
            integrity="sha512-Tn2m0TIpgVyTzzvmxLNuqbSJH3JP8jm+Cy3hvHrW7ndTDcJ1w5mBiksqDBb8GpE2ksktFvDB/ykZ0mDpsZj20w=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.3.6/dist/sweetalert2.all.min.js"></script>

    @*datable*@
    <script src="~/lib/dataTable/datatables.min.js"></script>
    <script src="~/lib/dataTable/DataTables-1.13.3/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/dataTable/Buttons-2.3.5/js/buttons.bootstrap4.min.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

<script>
    $(document).ready(function () {

    });

    function modalProcesando(desplegar) {
        if (desplegar) {
            $("#container-modal-procesando").modal({ backdrop: 'static', keyboard: false });
        } else {
            setTimeout(function () {
                $('#container-modal-procesando').modal('hide');
            }, 500);
        }
    }

    function toastMessage(type, message) {
        const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.addEventListener('mouseenter', Swal.stopTimer)
                toast.addEventListener('mouseleave', Swal.resumeTimer)
            }
        });

        Toast.fire({
            icon: type,
            title: message
        });
    }


</script>

MyVet/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyVet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
</head>
<body>
 
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyVet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>